name: build

on:
  push:
    branches: ["master", "preparation"]
  pull_request:
    branches: ["master", "preparation"]


jobs:
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: FetchSourceCode
        uses: actions/checkout@v3
      - name: SecretScan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false
          GITLEAKS_ENABLE_SUMMARY: true
        continue-on-error: true
  semgrep:
    name: semgrep
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: FetchSourceCode
        uses: actions/checkout@v3
      - name: Semgrep
        run: semgrep ci --config=auto --sarif --output=semgrep.sarif || true
      - name: Upload
        uses: github/codeql-action/upload-sarif@v2
        with: 
          sarif_file: semgrep.sarif
        if: always()
        
